
******************TESTING**************************
11/01/2022, 08:54:06
test_fruit_is_in (__main__.MyTests) ... ok
test_hola (__main__.MyTests) ... FAIL

======================================================================
FAIL: test_hola (__main__.MyTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ale\Desktop\Programa Data Engeniere\Unidad 11\ejercicio_ejemplo2\tests\test.py", line 11, in test_hola
    self.assertEqual(valid_word, to_check)
AssertionError: 'Hola' != 'Chau'
- Hola
+ Chau


----------------------------------------------------------------------
Ran 2 tests in 0.002s

FAILED (failures=1)
